hello Microverse.
dunnyk/hello-microverse pull request #1
Opened 2022-03-19 14:31 UTC by dunnyk

- This is introduction to making my mobile website, stay with me.

2022-03-19 15:50 UTC, MeqdamAlqudah requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @dunnyk ,

Good job so far!
✔️ Good README and PR documentation
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-19 15:50 UTC, MeqdamAlqudah commented on index.html
> +<!DOCTYPE html>
- [ ] Please your branch name should describe a feature or some property
- [ ] Please the PR description should describe the changes that you have done in the PR
- [ OPTIONAL]  Please use present tense to write the commits
![image](https://user-images.githubusercontent.com/74744787/159128039-6a341cc2-232e-4c94-b396-ab36afbe8454.png)

2022-03-19 15:50 UTC, MeqdamAlqudah commented on README.md
> +- GitHub: [@dunnyk](https://github.com/dunnyk)
- [ ] Please add your name instead of Author

2022-03-19 17:36 UTC, dunnyk commented on README.md
> +- GitHub: [@dunnyk](https://github.com/dunnyk)
Do you mean I delete the branch I already have and commit changes from fresh, because after researching I realize, you can't rename the branch with a pull request open without deleting the branch and removing the pull request.

2022-03-19 17:39 UTC, MeqdamAlqudah commented on README.md
> +- GitHub: [@dunnyk](https://github.com/dunnyk)
Yes you can rename a branch please check this [article](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming)

2022-03-19 17:41 UTC, MeqdamAlqudah commented on README.md
> +- GitHub: [@dunnyk](https://github.com/dunnyk)
but it is so hard to change a commit that's
 why I call it Optional

2022-03-19 18:01 UTC, dunnyk commented on README.md
> +- GitHub: [@dunnyk](https://github.com/dunnyk)
I have done the changes requested.

2022-03-21 10:10 UTC, keroloussamy requested changes
Hi @dunnyk, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️

## Required Changes ♻️

- [ ] Kindly change your branch name you can see this [article](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch)

- [ ] Kindly add a descriptive description to your pull request, Like what changes you did in this pull request. You can click on the 3 dots and click `Edit` option and change the description.

![image](https://user-images.githubusercontent.com/35535130/159240474-c2d97572-8119-4e9b-ab75-83a300792886.png)


![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

## Optional suggestions
_Check the comments under the review._

- [ ] x

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-21 13:20 UTC, closed without merging

2022-03-21 14:25 UTC, dunnyk commented
I have changed my branch name from local development to hello-microverse.
Also I have add descriptive description to my pull request, as requested.

2022-03-21 14:57 UTC, keroloussamy commented
@dunnyk Okay ask for another review, with your new pull request

2022-03-21 15:08 UTC, dunnyk commented
please I don't get this clear, do you mean I go to the dashboard and do it
at actions?....
If yes, the options there lack Request Review... What do you advice.

On Mon, Mar 21, 2022 at 5:57 PM Kerolous Samy Grace <
***@***.***> wrote:

> @dunnyk <https://github.com/dunnyk> Okay ask for another review, with
> your new pull request
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dunnyk/hello-microverse/pull/1#issuecomment-1074002981>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQX3W7HHHKRWSWR5Q5FCLELVBCE5TANCNFSM5REC73NA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-21 15:40 UTC, keroloussamy commented
@dunnyk Yes for every project after you submit your first review if you got required changes you have to make these changes and after that go back to your dashboard and chose the Request Review option, and when you got approved you have also to click on submit option.

2022-03-21 16:02 UTC, dunnyk commented
Thank you for the clarification. I think the dashboard had not updated...
The option was lacking.

On Mon, Mar 21, 2022 at 6:41 PM Kerolous Samy Grace <
***@***.***> wrote:

> @dunnyk <https://github.com/dunnyk> Yes for every project after you
> submit your first review if you got required changes you have to make these
> changes and after that go back to your dashboard and chose the Request
> Review option, and when you got approved you have also to click on submit
> option.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dunnyk/hello-microverse/pull/1#issuecomment-1074057351>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQX3W7HQNUYGN3A5O2HNRWLVBCKBJANCNFSM5REC73NA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-21 16:31 UTC, keroloussamy commented
@dunnyk Kindly send me a screenshot

2022-03-21 16:33 UTC, dunnyk commented
of the merge or?....

On Mon, Mar 21, 2022 at 7:32 PM Kerolous Samy Grace <
***@***.***> wrote:

> @dunnyk <https://github.com/dunnyk> Kindly send me a screenshot
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dunnyk/hello-microverse/pull/1#issuecomment-1074129005>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQX3W7GPHZYUKFD4U5QLHL3VBCQANANCNFSM5REC73NA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-21 17:46 UTC, dunnyk commented
Ok, thanks. [image: image.png]

On Mon, Mar 21, 2022 at 7:43 PM Kerolous Samy Grace <
***@***.***> wrote:

> of your dashboard
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dunnyk/hello-microverse/pull/1#issuecomment-1074141064>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQX3W7BC3BR5GSAJJDBLOSLVBCRMXANCNFSM5REC73NA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>